export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_ADD ="ORDER_ADD";
export const ORDER_SAVE_SUCCES = 'ORDER_SAVE_SUCCES'
export const ORDER_SAVE_FAIL = 'ORDER_SAVE_FAIL'
export const ORDER_SAVE_REQUEST = 'ORDER_SAVE_REQUEST'